In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [8]:
print(result)

b'Hello World'


In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(20)

In [11]:
a + b
a + b
a + b

<tf.Tensor 'add_4:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [13]:
result

30

In [14]:
const = tf.constant(10)

In [15]:
fill_mat = tf.fill((4, 4), 10)

In [16]:
myzeros = tf.zeros((4, 4))

In [17]:
myones = tf.ones((4, 4))

In [18]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [19]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [20]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [21]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [22]:
sess = tf.InteractiveSession()

In [24]:
for op in my_ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 2.243093    0.43390796  0.09981178 -1.2780739 ]
 [ 0.4752996  -0.17942055 -0.04346064  0.15773888]
 [ 0.11665305  0.5060354  -0.18603115 -0.63165814]
 [-1.1302879   0.33657813  1.4473896  -0.10470271]]
[[0.01662505 0.5787169  0.8514309  0.3792919 ]
 [0.93374    0.18638206 0.8285388  0.14235342]
 [0.38308036 0.7927228  0.10455513 0.990839  ]
 [0.83540154 0.40244436 0.27875233 0.2889254 ]]


In [25]:
a = tf.constant([ [1, 2], 
                  [3, 4] ])

In [26]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [27]:
b = tf.constant([ [1], [100] ])

In [28]:
result = tf.matmul(a, b)

In [29]:
sess.run(result)

array([[201],
       [403]], dtype=int32)

In [30]:
result.eval()

array([[201],
       [403]], dtype=int32)